USE ecommerce;
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Classic Vegan Leather Handbag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.0, 1499.0, 'Essentials', 'handbag, tote, shoulder bag, womens fashion, amazon', 50, 2, 4.6, 25, 'https://m.media-amazon.com/images/I/41vuCvcRl6L._AC_SR250,250_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Elegance Crossbody Shoulder Bag', 'Material: Premium vegan leather | Features: Adjustable shoulder strap, sleek metallic hardware | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1599.0, 1299.0, 'Essentials', 'handbag, tote, shoulder bag, womens fashion, amazon', 50, 2, 4.6, 25, 'https://m.media-amazon.com/images/I/616UdQ1u6LL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');

INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Classic Vegan Leather Handbag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1699.0, 1399.0, 'Elegance', 'handbag, tote, shoulder bag, womens fashion, elegance', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/51B5i8VXffL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Elegance Quilted Crossbody Sling Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.0, 1199.0, 'Caprese', 'handbag, tote, shoulder bag, womens fashion, caprese', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/81ezZQAQT5L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Vintage Shoulder Leather Tote Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1899.0, 1599.0, 'Lavie', 'handbag, tote, shoulder bag, womens fashion, lavie', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/31R0W11vYpL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Handcrafted Canvas Printed Tote Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.0, 999.0, 'ZOUK', 'handbag, tote, shoulder bag, womens fashion, zouk', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/61T8wrAGPJL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Structured Satchel Designer Handbag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.0, 1499.0, 'Allen Solly', 'handbag, tote, shoulder bag, womens fashion, allen solly', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/51ivBuhty9L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Soft Pastel Hobo Shoulder Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1599.0, 1299.0, 'Lino Perros', 'handbag, tote, shoulder bag, womens fashion, lino perros', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/81ZZzCBJBUL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Luxe Evening Chain Strap Clutch', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1999.0, 1699.0, 'Miraggio', 'handbag, tote, shoulder bag, womens fashion, miraggio', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/714Xb1jFm2L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Classic Tan Leather Shopper Tote', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 2199.0, 1799.0, 'Fossil', 'handbag, tote, shoulder bag, womens fashion, fossil', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/51Dyn+hZz5L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Casual Slouchy Hobo Handbag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1399.0, 1099.0, 'Baggit', 'handbag, tote, shoulder bag, womens fashion, baggit', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/818G1ErGG+L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Minimalist Off-White Satchel Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1699.0, 1399.0, 'Van Heusen', 'handbag, tote, shoulder bag, womens fashion, van heusen', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/81oYaSWP+YL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Royal Tan Vegan Leather Satchel', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.0, 1499.0, 'Lavie', 'handbag, tote, shoulder bag, womens fashion, lavie', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/7122u+VXvOL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Quilted Black Crossbody Sling Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.0, 1199.0, 'Caprese', 'handbag, tote, shoulder bag, womens fashion, caprese', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/81oVJgUpJiL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Executive Vintage Leather Shoulder Bag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1899.0, 1599.0, 'B-MART Craft', 'handbag, tote, shoulder bag, womens fashion, b-mart craft', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/5184S6Ak3+L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Handmade Canvas Tote Handbag', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.0, 999.0, 'ZOUK', 'handbag, tote, shoulder bag, womens fashion, zouk', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/51OAsjGdjaL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Elegance Structured Leather Satchel', 'Material: Premium vegan leather | Features: Dual top handles, spacious main compartment, zip pocket | Occasion: Daily office, casual outings, and evening wear | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.0, 1499.0, 'Allen Solly', 'handbag, tote, shoulder bag, womens fashion, allen solly', 50, 2, 4.6, 28, 'https://m.media-amazon.com/images/I/61XMFN5YF4L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
