USE ecommerce;
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Hard Polycarbonate Spinner Luggage 65cm', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3299.0, 2499.0, 'American Tourister', 'travel bag, luggage, trolley, duffle, american tourister', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/7125e-CY3lL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Explorer Heavy Duty Canvas Weekender Duffle', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2199.0, 1699.0, 'B-MART Explorer', 'travel bag, luggage, trolley, duffle, b-mart explorer', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/71OwGFwkufL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Polycarbonate Cabin Trolley Suitcase 55cm', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2899.0, 2199.0, 'Aristocrat', 'travel bag, luggage, trolley, duffle, aristocrat', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/81ZCA88iWqL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Mountain Expedition Trekking Rucksack 60L', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2599.0, 1999.0, 'Wildcraft', 'travel bag, luggage, trolley, duffle, wildcraft', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/71wpQ+eRNpL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Trooper Hard Check-in Large Luggage 75cm', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3799.0, 2999.0, 'Skybags', 'travel bag, luggage, trolley, duffle, skybags', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/71tzEgzCFcL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Genuine Leather Overnight Weekender Duffle', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3499.0, 2699.0, 'B-MART Craft', 'travel bag, luggage, trolley, duffle, b-mart craft', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/61uCq+-EFjL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Teakwood Leathers Unisex Trolley Bag', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3999.0, 2999.0, 'Teakwood Leathers', 'travel bag, luggage, trolley, duffle, teakwood leathers', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/61blC+q78bL._AC_UF480,480_SR480,480_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Executive Rolling Duffle Travel Bag 70L', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2999.0, 2299.0, 'VIP', 'travel bag, luggage, trolley, duffle, vip', 50, 3, 4.7, 32, 'https://m.media-amazon.com/images/I/71LfykHIpsL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');

INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Expandable Cabin Carry-On Trolley', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3499.0, 2699.0, 'Samsonite', 'travel bag, luggage, trolley, duffle, samsonite', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/51QgC7jK42L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Lightweight Check-In Luggage Spinner', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2799.0, 2099.0, 'Nasher Miles', 'travel bag, luggage, trolley, duffle, nasher miles', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/61RLvERV7lL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Waterproof Gym & Travel Duffle Bag', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 1899.0, 1399.0, 'Safari', 'travel bag, luggage, trolley, duffle, safari', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/61jEoQ8CgkL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Heavy Duty Travel Rolling Suitcase', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3199.0, 2399.0, 'Aristocrat', 'travel bag, luggage, trolley, duffle, aristocrat', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/71LfykHIpsL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Hard Shell Spinner Cabin Trolley', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 3599.0, 2799.0, 'American Tourister', 'travel bag, luggage, trolley, duffle, american tourister', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/51PM-+81VZL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Handcrafted Leather Travel Weekender Duffle', 'Material: Premium durable material | Features: Heavy-duty zippers, 360-degree rotating wheels, spacious interior | Occasion: Perfect for travel, vacations, and business trips | Warranty: 1 Year B-MART Manufacturer Warranty.', 2999.0, 2299.0, 'B-MART Craft', 'travel bag, luggage, trolley, duffle, b-mart craft', 50, 3, 4.7, 28, 'https://m.media-amazon.com/images/I/61VMNi9GS5L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
