USE ecommerce;
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Bifold Genuine Italian Leather RFID Wallet', 'Material: Genuine Leather | Features: RFID blocking, multiple card slots, zip coin pocket | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 899.0, 699.0, 'B-MART Essentials', 'wallet, cardholder, leather, b-mart essentials', 50, 4, 4.5, 30, 'https://m.media-amazon.com/images/I/615S-Q04WbL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Charcoal Grey Nappa Leather Coin Pocket Wallet', 'Material: Genuine Leather | Features: RFID blocking, multiple card slots, zip coin pocket | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 799.0, 599.0, 'Titan', 'wallet, cardholder, leather, titan', 50, 4, 4.5, 30, 'https://m.media-amazon.com/images/I/613h5Iwf5GL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Slim Minimalist Front Pocket RFID Cardholder', 'Material: Genuine Leather | Features: RFID blocking, multiple card slots, zip coin pocket | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 499.0, 399.0, 'Hornbull', 'wallet, cardholder, leather, hornbull', 50, 4, 4.5, 30, 'https://m.media-amazon.com/images/I/71S0+Q8rjAL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');

INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Executive RFID Genuine Leather Bifold Wallet', 'Material: Genuine Leather | Features: RFID blocking, 14 card slots, 2 zipper compartments | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 849.0, 649.0, 'Contacts', 'wallet, cardholder, leather, contacts', 50, 4, 4.6, 35, 'https://m.media-amazon.com/images/I/71KQ8pMP12L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');

INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Vintage Slim RFID Blocking Leather Wallet', 'Material: Genuine Leather | Features: RFID blocking, multiple card slots, zip coin pocket | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 949.0, 749.0, 'WildHorn', 'wallet, cardholder, leather, wildhorn', 50, 4, 4.5, 25, 'https://m.media-amazon.com/images/I/71TY4WiVXJL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Executive Slim Leather Cardholder & Money Clip', 'Material: Genuine Leather | Features: RFID blocking, multiple card slots, zip coin pocket | Occasion: Daily use, office, and travel | Warranty: 1 Year B-MART Manufacturer Warranty.', 799.0, 599.0, 'Contacts', 'wallet, cardholder, leather, contacts', 50, 4, 4.5, 25, 'https://m.media-amazon.com/images/I/71KQ8pMP12L._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
