USE ecommerce;
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Red Lemon Swiss Polyester Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.0, 999.0, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_SWISS_POLYSTER_backpack3.jpg?updatedAt=1785153685640', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Mokobara Black Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1699.0, 1399.0, 'Mokobara', 'backpack, laptop, travel, mokobara', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/MOKABARA_BLACK_backpack8.jpg?updatedAt=1785153685634', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Red Lemon Titan Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1399.0, 1099.0, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_TITAN_backpack2.jpg?updatedAt=1785153685646', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Mokobara Red Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1599.0, 1299.0, 'Mokobara', 'backpack, laptop, travel, mokobara', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/MOKABARA_RED_backpack9.jpg?updatedAt=1785153685625', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Safari Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1199.0, 899.0, 'Safari', 'backpack, laptop, travel, safari', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/SAFARI_backpack6.jpg?updatedAt=1785153685480', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('United Colors Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1249.0, 949.0, 'United Colors', 'backpack, laptop, travel, united colors', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/UNITED_COLOR_backpack7.jpg?updatedAt=1785153685483', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Arctic Hunter Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.0, 1199.0, 'Arctic Hunter', 'backpack, laptop, travel, arctic hunter', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/ARCTIC_HUNTER_backpack4.jpg?updatedAt=1785153685516', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Everyday Casual Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1099.0, 799.0, 'Everyday Casual', 'backpack, laptop, travel, everyday casual', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/EVERYDAY_CASUAL_backpack5.jpg?updatedAt=1785153685616', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Teleport Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1399.0, 1099.0, 'Teleport', 'backpack, laptop, travel, teleport', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/TELEPORT_backpack11.jpg?updatedAt=1785153685682', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Red Lemon Swiss Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1349.0, 1049.0, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_SWISS_backpack1.jpg?updatedAt=1785153685760', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Skybags Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.0, 999.0, 'Skybags', 'backpack, laptop, travel, skybags', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/SKY_backpack13.jpg?updatedAt=1785153685719', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Gear Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1199.0, 899.0, 'Gear', 'backpack, laptop, travel, gear', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/GEAR_backpack14.jpg?updatedAt=1785153685770', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('ProArch Leather Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.0, 1499.0, 'ProArch', 'backpack, laptop, travel, proarch', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/ProArch_LEATHER_backpack12.jpg?updatedAt=1785153685722', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Wesley Vintage Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1249.0, 949.0, 'Wesley', 'backpack, laptop, travel, wesley', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/WESLEY_VINTAGE_backapck15.jpg?updatedAt=1785153685729', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Urban Premium Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.0, 1199.0, 'Essentials', 'backpack, laptop, travel, amazon', 50, 1, 4.5, 35, 'https://m.media-amazon.com/images/I/61-w32faZtL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');


INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Canvas Travel Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.0, 999.0, 'Basics', 'backpack, laptop, travel, amazon, basics', 50, 1, 4.5, 40, 'https://m.media-amazon.com/images/I/51yld7nYqmL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Executive Laptop Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1599.0, 1299.0, 'Basics', 'backpack, laptop, travel, amazon, basics', 50, 1, 4.5, 40, 'https://m.media-amazon.com/images/I/61MrpCufmDL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Anti-Theft Waterproof Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1699.0, 1399.0, 'Basics', 'backpack, laptop, travel, amazon, basics', 50, 1, 4.5, 40, 'https://m.media-amazon.com/images/I/61vbUBsVXgL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');
INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status)
VALUES ('Lightweight College Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1199.0, 899.0, 'Basics', 'backpack, laptop, travel, amazon, basics', 50, 1, 4.5, 40, 'https://m.media-amazon.com/images/I/41VXyKKc8LL._AC_UL640_FMwebp_QL65_.jpg', 'APPROVED');

