-- Seed Data for B-MART E-Commerce Database

USE ecommerce;

-- Insert 4 Core Categories
INSERT INTO categories (category_id, category_name, description, image_url) VALUES
(1, 'Backpacks', 'Ergonomic, spacious, and stylish backpacks for laptops, travel, college, and adventure.', '/uploads/backpacks/MOKABARA_BLACK_backpack8.jpg'),
(2, 'Handbags', 'Trendy leather and canvas handbags, totes, and satchels for daily style and elegance.', '/uploads/handbags/handbag1.jpg'),
(3, 'Travel Bags', 'Durable duffle bags, trolley luggage, and weekenders designed for effortless journeys.', '/uploads/travelbags/travel1.jpg'),
(4, 'Wallets', 'Sleek RFID-protected leather wallets, slim cardholders, and stylish zip clutches.', '/uploads/wallets/wallet1.jpg')
ON DUPLICATE KEY UPDATE category_name=VALUES(category_name), description=VALUES(description), image_url=VALUES(image_url);

INSERT INTO products (name, description, price, discount_price, brand, tags, stock, category_id, rating, review_count, image_url, status) VALUES
('Switch Convertible Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.00, 1199.00, 'Switch', 'backpack, laptop, travel, switch', 50, 1, 4.5, 28, 'https://ik.imagekit.io/StringStackAnil/BackPacks/SWITCH_CONVERTIBLE_backpack10.jpg?updatedAt=1785153685828', 'APPROVED'),
('Red Lemon Swiss Polyester Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.00, 999.00, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_SWISS_POLYSTER_backpack3.jpg?updatedAt=1785153685640', 'APPROVED'),
('Mokobara Black Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1699.00, 1399.00, 'Mokobara', 'backpack, laptop, travel, mokobara', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/MOKABARA_BLACK_backpack8.jpg?updatedAt=1785153685634', 'APPROVED'),
('Red Lemon Titan Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1399.00, 1099.00, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_TITAN_backpack2.jpg?updatedAt=1785153685646', 'APPROVED'),
('Mokobara Red Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1599.00, 1299.00, 'Mokobara', 'backpack, laptop, travel, mokobara', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/MOKABARA_RED_backpack9.jpg?updatedAt=1785153685625', 'APPROVED'),
('Safari Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1199.00, 899.00, 'Safari', 'backpack, laptop, travel, safari', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/SAFARI_backpack6.jpg?updatedAt=1785153685480', 'APPROVED'),
('United Colors Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1249.00, 949.00, 'United Colors', 'backpack, laptop, travel, united colors', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/UNITED_COLOR_backpack7.jpg?updatedAt=1785153685483', 'APPROVED'),
('Arctic Hunter Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1499.00, 1199.00, 'Arctic Hunter', 'backpack, laptop, travel, arctic hunter', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/ARCTIC_HUNTER_backpack4.jpg?updatedAt=1785153685516', 'APPROVED'),
('Everyday Casual Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1099.00, 799.00, 'Everyday Casual', 'backpack, laptop, travel, everyday casual', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/EVERYDAY_CASUAL_backpack5.jpg?updatedAt=1785153685616', 'APPROVED'),
('Teleport Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1399.00, 1099.00, 'Teleport', 'backpack, laptop, travel, teleport', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/TELEPORT_backpack11.jpg?updatedAt=1785153685682', 'APPROVED'),
('Red Lemon Swiss Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1349.00, 1049.00, 'Red Lemon', 'backpack, laptop, travel, red lemon', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/RED_LEMON_SWISS_backpack1.jpg?updatedAt=1785153685760', 'APPROVED'),
('Skybags Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1299.00, 999.00, 'Skybags', 'backpack, laptop, travel, skybags', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/SKY_backpack13.jpg?updatedAt=1785153685719', 'APPROVED'),
('Gear Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1199.00, 899.00, 'Gear', 'backpack, laptop, travel, gear', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/GEAR_backpack14.jpg?updatedAt=1785153685770', 'APPROVED'),
('ProArch Leather Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1799.00, 1499.00, 'ProArch', 'backpack, laptop, travel, proarch', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/ProArch_LEATHER_backpack12.jpg?updatedAt=1785153685722', 'APPROVED'),
('Wesley Vintage Backpack', 'Material: Premium durable material | Features: Multi-compartment organizer with heavy-duty metal zippers | Occasion: Perfect for daily use, travel, office, and gifts | Warranty: 1 Year B-MART Manufacturer Warranty.', 1249.00, 949.00, 'Wesley', 'backpack, laptop, travel, wesley', 50, 1, 4.5, 30, 'https://ik.imagekit.io/StringStackAnil/BackPacks/WESLEY_VINTAGE_backapck15.jpg?updatedAt=1785153685729', 'APPROVED');
